name: "Versioning"
description: "Tags repository with the next version"

runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Tag with next release version"
      shell: bash
      run: |
        if [ -z $env.pr_name ]; then
            env.pr_name="New PR on $(date)"
        fi
        ./scripts/pipeline/version.sh ${{ env.pr_name }} ${{ env.version_bump }}
    # - name: "create tagged versions of lambdas"
    #   run: |
    #     echo "TODO: create release versions of lambdas"
    # - name: "create tagged versions of frontend"
    #   run: |
    #     echo "TODO: create release versions of lambdas"
    # - name: "create tagged versions of frontend"
    #   run: |
    #     echo "TODO: tag main branch"
