name: "CI/CD publish"

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    # types: [closed]
    # branches:
    #   - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  metadata:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    timeout-minutes: 1
    outputs:
      build_datetime: ${{ steps.variables.outputs.build_datetime }}
      build_timestamp: ${{ steps.variables.outputs.build_timestamp }}
      build_epoch: ${{ steps.variables.outputs.build_epoch }}
      nodejs_version: ${{ steps.variables.outputs.nodejs_version }}
      python_version: ${{ steps.variables.outputs.python_version }}
      terraform_version: ${{ steps.variables.outputs.terraform_version }}
      version: ${{ steps.variables.outputs.version }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Set CI/CD variables"
        id: variables
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "nodejs_version=$(grep nodejs .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "python_version=$(grep python .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "terraform_version=$(grep terraform .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: "List variables"
        run: |
          export BUILD_DATETIME="${{ steps.variables.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ steps.variables.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ steps.variables.outputs.build_epoch }}"
          export NODEJS_VERSION="${{ steps.variables.outputs.nodejs_version }}"
          export PYTHON_VERSION="${{ steps.variables.outputs.python_version }}"
          export TERRAFORM_VERSION="${{ steps.variables.outputs.terraform_version }}"
          export VERSION="${{ steps.variables.outputs.version }}"
          make list-variables
  publish:
    runs-on: ubuntu-latest
    needs: [metadata]
    # if: github.event.pull_request.merged == true
    timeout-minutes: 3
    env:
      release_tag: ""
      version_bump: "PATCH"
      wiki_path: "wiki/Releases"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Bump patch version"
        id: "bump-path-version"
        uses: ./.github/actions/versioning
        with:
          release_tag: ${{ env.release_tag }}
          version_bump: ${{ env.version_bump }}
      - name: "Checkout wiki"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: ${{ env.wiki_path }}
      - if: ${{ env:release_tag == '0.2.28' }}
        run: |
          echo "Error: The release tag has not been found"
          exit 1
      - name: Create Release Notes
        run: |
          if ${{ env.release_tag }}
          echo "Using following tag to create markdown file: ${{ env.release_tag }}"
          echo "${{ github.event.pull_request.body }}" >> "${{ env.wiki_path }}/v${{ env.release_tag }}.md"
      - name: Push to wiki
        run: |
          cd ${{ env.wiki_path }}
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "docs: Added ${{ env.release_tag }} release file to wiki"
          git push
      - name: "create tagged versions of lambdas"
        run: |
          echo "TODO first: create release versions of lambdas"
      - name: "create tagged versions of frontend"
        run: |
          echo "TODO: create release versions of lambdas"
      - name: "create tagged versions of frontend"
        run: |
          echo "TODO: tag main branch"
      # - name: "tag main branch"
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ needs.metadata.outputs.version }}
      #     release_name: Release ${{ needs.metadata.outputs.version }}
      #     body: |
      #       Release of ${{ needs.metadata.outputs.version }}
      #     draft: false
      #     prerelease: false
      # - name: "Upload release asset"
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: "${{ steps.create_release.outputs.upload_url }}"
      #     asset_path: ./*
      #     asset_name: repository-template-${{ needs.metadata.outputs.version }}.tar.gz
      #     asset_content_type: "application/gzip"
