name: "Performance Test 1"

# The total recommended execution time for the "CI/CD Pull Request" workflow is around 20 minutes.

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      invitations_branch:
        description: "This is the branch/tag of Galleri-Invitations be deployed to the Performance environment"
        required: true
      frontend_branch:
        description: "This is the branch/tag of the Galleri frontend to be deployed to the Performance environment"
        required: true
      database_seeding:
        description: "Determines if the seeding scripts are run to populate the database"
        type: choice
        required: true
        default: "yes"
        options:
          - "yes"
          - "no"
      tf_action:
        type: choice
        description: Terraform action to be carried out against UAT environment
        required: true
        default: apply
        options:
          - apply
          - destroy
      test:
        type: choice
        description: Should tests be run?
        required: true
        default: "no"
        options:
          - "yes"
          - "no"

jobs:
  metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      environment: "performance"
    outputs:
      build_datetime_london: ${{ steps.variables.outputs.build_datetime_london }}
      build_datetime: ${{ steps.variables.outputs.build_datetime }}
      build_timestamp: ${{ steps.variables.outputs.build_timestamp }}
      build_epoch: ${{ steps.variables.outputs.build_epoch }}
      nodejs_version: ${{ steps.variables.outputs.nodejs_version }}
      python_version: ${{ steps.variables.outputs.python_version }}
      terraform_version: ${{ steps.variables.outputs.terraform_version }}
      version: ${{ steps.variables.outputs.version }}
      does_pull_request_exist: ${{ steps.pr_exists.outputs.does_pull_request_exist }}
      environment: ${{ env.environment }}
      invitations_branch: ${{ github.event.inputs.invitations_branch }}
      frontend_branch: ${{ github.event.inputs.invitations_branch }}
      database_seeding: ${{ github.event.inputs.database_seeding }}
      tf_action: ${{ github.event.inputs.tf_action }}
      test: ${{ github.event.inputs.test }}
    steps:
      - name: "print environment name"
        run: |
          echo job running on branch: ${{ github.base_ref }}
          echo environment is: ${{ env.environment }}
          echo seed database: ${{ github.event.inputs.database_seeding }}
          echo run tests: ${{ github.event.inputs.test }}
          echo terraform action: ${{ github.event.inputs.tf_action }}
          echo frontend branch: ${{ github.event.inputs.frontend_branch }}
          echo invitations_branch: ${{ github.event.inputs.invitations_branch }}
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.invitations_branch }}
      - name: "Set CI/CD variables"
        id: variables
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime_london=$(TZ=Europe/London date --date=$datetime +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_OUTPUT
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "nodejs_version=$(grep nodejs .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "python_version=$(grep python .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "terraform_version=$(grep terraform .tool-versions | cut -f2 -d' ')" >> $GITHUB_OUTPUT
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "environment=performance" >> $GITHUB_OUTPUT
      - name: "Check if pull request exists for this branch"
        id: pr_exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's#refs/heads/##')}
          echo "Current branch is '$branch_name'"
          if gh pr list --head $branch_name | grep -q .; then
            echo "Pull request exists"
            echo "does_pull_request_exist=true" >> $GITHUB_OUTPUT
          else
            echo "Pull request doesn't exist"
            echo "does_pull_request_exist=false" >> $GITHUB_OUTPUT
          fi
      - name: "List variables"
        run: |
          export BUILD_DATETIME_LONDON="${{ steps.variables.outputs.build_datetime_london }}"
          export BUILD_DATETIME="${{ steps.variables.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ steps.variables.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ steps.variables.outputs.build_epoch }}"
          export NODEJS_VERSION="${{ steps.variables.outputs.nodejs_version }}"
          export PYTHON_VERSION="${{ steps.variables.outputs.python_version }}"
          export TERRAFORM_VERSION="${{ steps.variables.outputs.terraform_version }}"
          export VERSION="${{ steps.variables.outputs.version }}"
          export DOES_PULL_REQUEST_EXIST="${{ steps.pr_exists.outputs.does_pull_request_exist }}"
          make list-variables

  performance-stage:
    runs-on: ubuntu-latest
    needs: [metadata]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "git tag with next release version"
        shell: bash
        run: |
          ./scripts/pipeline/version.sh MINOR
      # - name: "create tagged versions of lambdas"
      #   run: |
      #     echo "TODO: create release versions of lambdas"
      # - name: "create tagged versions of frontend"
      #   run: |
      #     echo "TODO: create release versions of lambdas"
      # - name: "create tagged versions of frontend"
      #   run: |
      #     echo "TODO: tag main branch"
      - name: "run performance check against latest versions"
        run: |
          JMETER_VERSION="5.6.3"
          curl https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz -o apache-jmeter.tgz
          tar -xvzf apache-jmeter.tgz
          ./apache-jmeter-$JMETER_VERSION/bin/jmeter --version
          curl https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar -o apache-jmeter-$JMETER_VERSION/lib/cmdrunner-2.3.jar
          curl https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar -o apache-jmeter-$JMETER_VERSION/lib/ext/jmeter-plugins-manager-1.10.jar
          java -cp apache-jmeter-$JMETER_VERSION/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          cd apache-jmeter-$JMETER_VERSION/bin
          ./PluginsManagerCMD.sh install-for-jmx $GITHUB_WORKSPACE/scripts/test/perftest/NHS_Galleri_Perf_Test_v1.0.jmx
          ./jmeter -n -t $GITHUB_WORKSPACE/scripts/test/perftest/NHS_Galleri_Perf_Test_v1.0.jmx -l $GITHUB_WORKSPACE/result.jtl
          cat $GITHUB_WORKSPACE/result.jtl
      - name: "Upload Performance Test Results"
        uses: actions/upload-artifact@v3
        with:
          name: performance-test-result
          path: result.jtl

  commit-stage: # Recommended maximum execution time is 2 minutes
    needs: [metadata]
    uses: ./.github/workflows/stage-1-commit.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
      invitations_branch: "${{ github.event.inputs.invitations_branch }}"
    secrets: inherit
  test-stage: # Recommended maximum execution time is 5 minutes
    needs: [metadata, commit-stage]
    uses: ./.github/workflows/stage-2-test.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
      invitations_branch: "${{ github.event.inputs.invitations_branch }}"
    secrets: inherit

  build-stage: # Recommended maximum execution time is 10 minutes
    needs: [metadata, test-stage]
    uses: ./.github/workflows/stage-3-build.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
      environment: ${{ needs.metadata.outputs.environment }}
      invitations_branch: "${{ github.event.inputs.invitations_branch }}"
      frontend_branch: "${{ github.event.inputs.frontend_branch }}"
      tf_action: "${{ github.event.inputs.tf_action }}"
    secrets: inherit

  data-stage: # Recommended maximum execution time is 10 minutes
    needs: [metadata, test-stage, build-stage]
    uses: ./.github/workflows/stage-4-load-data.yaml
    if: needs.metadata.outputs.database_seeding == 'yes'
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
      environment: ${{ needs.metadata.outputs.environment }}
    secrets: inherit

  acceptance-stage: # Recommended maximum execution time is 10 minutes
    needs: [metadata, test-stage, build-stage, data-stage]
    uses: ./.github/workflows/stage-5-acceptance.yaml
    if: needs.metadata.outputs.test == 'yes' && (needs.data-stage.result == 'success' || needs.data-stage.result == 'skipped')
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      build_epoch: "${{ needs.metadata.outputs.build_epoch }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
      python_version: "${{ needs.metadata.outputs.python_version }}"
      terraform_version: "${{ needs.metadata.outputs.terraform_version }}"
      version: "${{ needs.metadata.outputs.version }}"
      environment: ${{ needs.metadata.outputs.environment }}
    secrets: inherit
