name: hello-world
on:
  workflow_call:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: my-step
        run: echo "Hello World!"
